name: podpublish
version: 0.0.3
summary: A tool for encoding and publishing podcast content and assets
description: |
 A tool for encoding and publishing podcast content and assets. Inspired by
 bv-publish and the talk Stuart Langridge gave at Oggcamp 2015. Project created
 by Ubuntu Podcast and released under the GPLv2 license.

confinement: strict
grade: stable

# Export LC_ALL to work-around (LP: #1576411)
apps:
  encode-podcast:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/encode-podcast
    plugs: [home]
  publish-podcast:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/publish-podcast
    plugs: [home, network]
  season-to-youtube:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/season-to-youtube
    plugs: [home]
  youtube-upload:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/youtube-upload
    plugs: [home, network]

parts:
  podpublish:
    plugin: python
    requirements: requirements.txt
    source: .
    after:
      - ffmpeg
    build-packages:
      - gcc
      - liblcms2-dev
      - libffi-dev
      - libfreetype6-dev
      - libjpeg8-dev
      - libopenjp2-7-dev
      - libssl-dev
      - libtiff5-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - liblcms2-2
      - libffi6
      - libfreetype6
      - libjpeg8
      - libopenjp2-7
      - libssl1.0.0
      - libtiff5
      - zlib1g
    # The cruft_ filesets define files/directories that can be safely removed
    # from podpublish to reduce the size of the snap. They have been grouped
    # to assist others seeking to shrink snaps of Python apps.
    filesets:
      cruft_binaries:
        - -bin/*.py
        - -bin/html2text
        - -bin/markdown_py
        - -bin/mid3*
        - -bin/moggsplit
        - -bin/mutagen*
        - -bin/pyrsa*
        - -usr/bin/pydoc3*
        - -usr/bin/pygettext3*
        - -usr/sbin
      cruft_compilers_and_debuggers:
        - -usr/bin/pdb3*
        - -usr/lib/gcc
        - -usr/lib/valgrind
        - -usr/share/bug
      cruft_debhelper:
        - -usr/bin/dh_*
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/perl5/Debian
      cruft_docs:
        - -usr/share/doc
        - -usr/share/doc-base
      cruft_fonts:
        - -usr/share/fonts
      cruft_headers:
        - -usr/share/include
      cruft_lintian:
        - -usr/share/lintian/overrides
      cruft_man_pages:
        - -usr/share/man
        - -share/man
      cruft_meta:
        - -usr/share/applications
        - -usr/share/pixmaps
      cruft_python_2to3:
        - -usr/bin/2to3*
        - -usr/lib/python*/lib2to3
      cruft_python_idle:
        - -usr/lib/python*/idlelib
        - -usr/lib/python*/tkinter
      cruft_python_pip:
        - -lib/python*/site-packages/pip
      cruft_python_setuptools:
        - -lib/python*/site-packages/setuptools*
      cruft_python_tests:
        - -lib/python*/site-packages/tests
      cruft_python_venv:
        - -usr/lib/python*/venv
      cruft_python_wheel:
        - -lib/python*/site-packages/wheel*
      cruft_x11:
        - -usr/share/X11/XErrorDB
    snap:
      - $cruft_binaries
      - $cruft_compilers_and_debuggers
      - $cruft_debhelper
      - $cruft_docs
      - $cruft_fonts
      - $cruft_headers
      - $cruft_lintian
      - $cruft_man_pages
      - $cruft_python_2to3
      - $cruft_python_idle
      - $cruft_python_pip
      - $cruft_python_setuptools
      - $cruft_python_tests
      - $cruft_python_venv
      - $cruft_python_wheel
      - $cruft_x11

# Cut down ffmpeg specific to podpublish needs
  ffmpeg:
    source: http://ffmpeg.org/releases/ffmpeg-3.2.tar.bz2
    plugin: autotools
    configflags:
      - --enable-gpl
      - --enable-nonfree
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libx264
      - --disable-avdevice
      - --disable-doc
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --disable-libass
      - --disable-libopus
      - --disable-libtheora
      - --disable-libvpx
      - --disable-libx265
    build-packages:
      - gcc
      - libfreetype6-dev
      - libmp3lame-dev
      - libvorbis-dev
      - libx264-dev
      - pkg-config
      - yasm
      - zlib1g-dev
    organize:
      usr/local/bin: usr/bin
    snap:
      - usr/bin/ffmpeg
