name: podpublish
version: 20160610+git5ddfa04-1
summary: A tool for encoding and publishing podcast content and assets
description: |
 A tool for encoding and publishing podcast content and assets. Inspired by
 bv-publish and the talk Stuart Langridge gave at Oggcamp 2015. Project created
 by Ubuntu Podcast and released under the GPLv2 license.

confinement: devmode
grade: devel

apps:
  encode-podcast:
    command: usr/bin/python3 $SNAP/usr/bin/encode-podcast
    plugs: [home]
  publish-podcast:
    command: usr/bin/python3 $SNAP/usr/bin/publish-podcast
    plugs: [home, network]
  season-to-youtube:
    command: usr/bin/python3 $SNAP/usr/bin/season-to-youtube
    plugs: [home]
  youtube-upload:
    command: usr/bin/python3 $SNAP/usr/bin/youtube-upload
    plugs: [home, network]

parts:
  podpublish:
    plugin: python
    requirements: requirements.txt
    source: https://bitbucket.org/flexiondotorg/podpublish.git
    source-type: git
    build-packages:
      - build-essential
      - liblcms2-dev
      - libffi-dev
      - libfreetype6-dev
      - libjpeg8-dev
      - libopenjp2-7-dev
      - libssl-dev
      - libtiff5-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - liblcms2-2
      - libffi6
      - libfreetype6
      - libjpeg8
      - libopenjp2-7
      - libpulse0
      - libssl1.0.0
      - libtiff5
      - zlib1g
    snap:
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/fonts
      - -usr/share/include
      - -usr/share/man
      - -usr/share/X11/XErrorDB

  ffmpeg:
    source: http://ffmpeg.org/releases/ffmpeg-3.2.tar.bz2
    plugin: autotools
    configflags: [--enable-gpl, --enable-libass, --enable-libfreetype, --enable-libmp3lame, --enable-libopus, --enable-libtheora, --enable-libvorbis, --enable-libvpx, --enable-libx264, --enable-libx265, --enable-nonfree]
    build-packages:
      - build-essential
      - cmake
      - libtool
      - pkg-config
      - libass-dev
      - libfreetype6-dev
      - libmp3lame-dev
      - libopus-dev
      - libsdl1.2-dev
      - libtheora-dev
      - libva-dev
      - libvdpau-dev
      - libvorbis-dev
      - libvpx-dev
      - libx264-dev
      - libx265-dev
      - libxcb1-dev
      - libxcb-shm0-dev
      - libxcb-xfixes0-dev
      - texinfo
      - yasm
      - zlib1g-dev
    organize:
      usr/local/bin: usr/bin
