name: podpublish
version: 0.0.2
summary: A tool for encoding and publishing podcast content and assets
description: |
 A tool for encoding and publishing podcast content and assets. Inspired by
 bv-publish and the talk Stuart Langridge gave at Oggcamp 2015. Project created
 by Ubuntu Podcast and released under the GPLv2 license.

confinement: devmode
grade: devel

# Export LC_ALL to work-around (LP: #1576411)
apps:
  encode-podcast:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/encode-podcast
    plugs: [home]
  publish-podcast:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/publish-podcast
    plugs: [home, network]
  season-to-youtube:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/season-to-youtube
    plugs: [home]
  youtube-upload:
    command: env LC_ALL=C.UTF-8 ${SNAP}/usr/bin/python3 $SNAP/bin/youtube-upload
    plugs: [home, network]

parts:
  podpublish:
    plugin: python
    requirements: requirements.txt
    source: https://bitbucket.org/flexiondotorg/podpublish.git
    source-type: git
    after:
      - ffmpeg
    build-packages:
      - gcc
      - liblcms2-dev
      - libffi-dev
      - libfreetype6-dev
      - libjpeg8-dev
      - libopenjp2-7-dev
      - libssl-dev
      - libtiff5-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - liblcms2-2
      - libffi6
      - libfreetype6
      - libjpeg8
      - libopenjp2-7
      - libssl1.0.0
      - libtiff5
      - zlib1g
    snap:
      - -bin/*.py
      - -bin/html2text
      - -bin/markdown_py
      - -bin/mid3*
      - -bin/moggsplit
      - -bin/mutagen*
      - -bin/pyrsa*
      - -lib/python*/site-packages/pip
      - -lib/python*/site-packages/setuptools*
      - -lib/python*/site-packages/tests
      - -lib/python*/site-packages/wheel*
      - -usr/bin/2to3*
      - -usr/bin/dh_*
      - -usr/bin/pdb3*
      - -usr/bin/pydoc3*
      - -usr/bin/pygettext3*
      - -usr/lib/gcc
      - -usr/lib/valgrind
      - -usr/sbin
      - -usr/share/applications
      - -usr/share/bug
      - -usr/share/debhelper
      - -usr/share/dh-python
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/fonts
      - -usr/share/include
      - -usr/share/lintian/overrides
      - -usr/share/man
      - -usr/share/perl5/Debian
      - -usr/share/pixmaps
      - -usr/share/X11/XErrorDB
      - -share/man

# Cut down ffmpeg specific to podpublish needs
  ffmpeg:
    source: http://ffmpeg.org/releases/ffmpeg-3.2.tar.bz2
    plugin: autotools
    configflags:
      - --enable-gpl
      - --enable-nonfree
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libx264
      - --disable-doc
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --disable-libass
      - --disable-libopus
      - --disable-libtheora
      - --disable-libvpx
      - --disable-libx265
    build-packages:
      - cmake
      - gcc
      - libfreetype6-dev
      - libmp3lame-dev
      - libvorbis-dev
      - libx264-dev
      - pkg-config
      - yasm
      - zlib1g-dev
    snap:
      - usr/bin/ffmpeg
    organize:
      usr/local/bin: usr/bin
