name: podpublish
version: git
version-script: |
  VER=$(grep __version__ podpublish/__init__.py  | cut -d'=' -f2 | sed 's/ //g' | sed "s/'//g")
  REV=$(git rev-parse --short HEAD)
  echo $VER-$REV
summary: A tool for encoding and publishing podcast content and assets
description: |
 A tool for encoding and publishing podcast content and assets. Inspired by
 bv-publish and the talk Stuart Langridge gave at Oggcamp 2015. Project created
 by Ubuntu Podcast and released under the GPLv2 license.

confinement: strict
grade: stable

parts:
  podpublish:
    plugin: python
    requirements: requirements.txt
    source: .
    after:
      - ffmpeg
    build-packages:
      - gcc
      - liblcms2-dev
      - libffi-dev
      - libfreetype6-dev
      - libjpeg8-dev
      - libopenjp2-7-dev
      - libssl-dev
      - libtiff5-dev
      - pkg-config
      - zlib1g-dev
    stage-packages:
      - liblcms2-2
      - libffi6
      - libfreetype6
      - libjpeg8
      - libopenjp2-7
      - libssl1.0.0
      - libtiff5
      - zlib1g
    # The cruft_ filesets define files/directories that can be safely removed
    # from podpublish to reduce the size of the snap. They have been grouped
    # to assist others seeking to shrink snaps of Python apps.
    filesets:
      cruft_binaries:
        - -bin/*.py
        - -bin/html2text
        - -bin/markdown_py
        - -bin/mid3*
        - -bin/moggsplit
        - -bin/mutagen*
        - -bin/pyrsa*
        - -usr/bin/pydoc3*
        - -usr/bin/pygettext3*
        - -usr/sbin
      cruft_compilers_and_debuggers:
        - -usr/bin/pdb3*
        - -usr/lib/gcc
        - -usr/lib/valgrind
        - -usr/share/bug
      cruft_debhelper:
        - -usr/bin/dh_*
        - -usr/share/debhelper
        - -usr/share/dh-python
        - -usr/share/perl5/Debian
      cruft_docs:
        - -usr/share/doc
        - -usr/share/doc-base
      cruft_fonts:
        - -usr/share/fonts
      cruft_headers:
        - -usr/share/include
      cruft_lintian:
        - -usr/share/lintian/overrides
      cruft_man_pages:
        - -usr/share/man
        - -share/man
      cruft_meta:
        - -usr/share/applications
        - -usr/share/pixmaps
      cruft_python_2to3:
        - -usr/bin/2to3*
        - -usr/lib/python*/lib2to3
      cruft_python_idle:
        - -usr/lib/python*/idlelib
        - -usr/lib/python*/tkinter
      cruft_python_pip:
        - -lib/python*/site-packages/pip
      cruft_python_tests:
        - -lib/python*/site-packages/tests
      cruft_python_venv:
        - -usr/lib/python*/venv
      cruft_python_wheel:
        - -lib/python*/site-packages/wheel*
      cruft_x11:
        - -usr/share/X11/XErrorDB
    prime:
      - $cruft_binaries
      - $cruft_compilers_and_debuggers
      - $cruft_debhelper
      - $cruft_docs
      - $cruft_fonts
      - $cruft_headers
      - $cruft_lintian
      - $cruft_man_pages
      - $cruft_python_2to3
      - $cruft_python_idle
      - $cruft_python_pip
      - $cruft_python_tests
      - $cruft_python_venv
      - $cruft_python_wheel
      - $cruft_x11

  nv-codec-headers:
    plugin: make
    source: https://github.com/FFmpeg/nv-codec-headers/releases/download/n8.2.15.4/nv-codec-headers-8.2.15.4.tar.gz
    override-build: |
      make install PREFIX=/usr
    build-packages:
      - pkg-config

  nasm:
    plugin: autotools
    source: http://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz
    configflags:
      - --prefix=/usr

  x264:
    plugin: autotools
    source: http://ftp.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-20181030-2245-stable.tar.bz2
    configflags:
      - --prefix=/usr
      - --disable-cli
      - --enable-pic
      - --enable-shared
      - --enable-strip
    after:
      - nasm
    prime:
      - usr/lib

  fdk-aac:
    plugin: autotools
    source: https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
    build-packages:
      - g++
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - usr/lib

  lame:
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --disable-static
      - --enable-nasm
    source: http://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
    prime:
      - usr/lib

  libogg:
    plugin: autotools
    source: http://downloads.xiph.org/releases/ogg/libogg-1.3.3.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share

  libvorbis:
    plugin: autotools
    source: http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-static
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share
    after:
      - libogg

# Cut down ffmpeg specific to podpublish needs
  ffmpeg:
    source: http://ffmpeg.org/releases/ffmpeg-4.0.2.tar.bz2
    plugin: autotools
    after:
     - nv-codec-headers
     - x264
     - fdk-aac
     - libvorbis
     - lame
    configflags:
      - --enable-gpl
      - --enable-nonfree
      - --enable-libfreetype
      - --enable-libmp3lame
      - --enable-libvorbis
      - --enable-libx264
      - --disable-avdevice
      - --disable-doc
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-libass
      - --disable-libopus
      - --disable-libtheora
      - --disable-libvpx
      - --disable-libx265
    build-packages:
      - gcc
      - libfreetype6-dev
      - pkg-config
      - yasm
      - zlib1g-dev
    organize:
      usr/local/bin: usr/bin
    prime:
      - usr/bin/ffmpeg

# Export LC_ALL to work-around http://pad.lv/1576411
apps:
  encode-podcast:
    command: usr/bin/python3 $SNAP/bin/encode-podcast
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - opengl
  publish-podcast:
    command: usr/bin/python3 $SNAP/bin/publish-podcast
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - ssh-keys
      - gpg-keys
  season-to-youtube:
    command: usr/bin/python3 $SNAP/bin/season-to-youtube
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
  youtube-upload:
    command: usr/bin/python3 $SNAP/bin/youtube-upload
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
